
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Biuld ansible-lint
        uses: ./.github/actions/ansible
      - name: Run ansible-lint
        run: cat /etc/hostname && ansible-lint run.yml
