
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Biuld ansible image and run command
        uses: ./.github/actions/ansible
        with: |
          cat /etc/hostname
          ansible-lint run.yml
