
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  verify:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: ansible-lint
        uses: ./.github/actions/ansible-lint
        with:
          targets: |
            run.yml
