
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/ansible
        with:
          command: ansible-lint run.yml
  syntax-check:
    needed: lint
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v2
        - uses: ./.github/actions/ansible
          with:
            command: ansible-playbook -i inventory/development --check run.yml
