
name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/ansible
        with:
          command: ansible-lint -v *.yml
  syntax-check:
    needs: lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/ansible
        with:
          command: ansible-playbook -i inventory/development --syntax-check *.yml
