
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  verify:
    # runs-on: ubuntu-20.04
    runs-on: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: ansible-lint
        uses: ansible/ansible-lint-action@master
        with:
          targets: |
            run.yml
